# Generated by Django 4.2.6 on 2023-10-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('result', models.SmallIntegerField(choices=[(1, 'Positive'), (-1, 'Negative')])),
            ],
        ),
    ]
