# Generated by Django 4.2.6 on 2023-10-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0005_rename_result_urlrecord_url_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlrecord',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
