# Generated by Django 4.2.6 on 2023-10-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0006_alter_urlrecord_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlrecord',
            name='url',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
