# Generated by Django 4.2.6 on 2023-10-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0008_rename_url_length_urlrecord_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlrecord',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
